<section>
    <?php $c = new \core\Component('m-template-component', '{"label":"Componente de ejemplo","mydataobject":{"key1":"val1","key2":1}}', '
        Contenido del componente
    '); $c->print();?>
    <?php $c = new \core\Component('m-template-component', '{"label":"Componente de ejemplo","mydataobject":{"key1":"val1","key2":1}}', '
        Contenido del componente
    '); $c->print();?>
</section>