<section>
    <!-- Content Wrapper -->
    <div id="wrapper">
        <div class="container">
            <!-- Light version -->
            <div id="light" class="row text-center">
                <!-- Info -->
                <div class="info">
                    <img src="//pkfrom.github.io/404/assets/img/404-light.gif" alt="404 error" />
                    <!-- end Rabbit -->
                    <p>The page you are looking for was moved, removed,<br />
                        renamed or might never existed.</p>
                    <!--<a href="#" class="btn btn-brown">Contact Us</a>-->
                </div>
                <!-- end Info -->
            </div>
            <!-- End Light version -->

        </div>
        <!-- end container -->
    </div>
    <!-- end Content Wrapper -->


    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="//pkfrom.github.io/404/assets/js/modernizr.custom.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.0/jquery.nicescroll.min.js" type="text/javascript"></script>
    <script src="//pkfrom.github.io/404/assets/js/404.min.js" type="text/javascript"></script>

</section>