<section>
    <h2>BONE</h2>
    <p>Directivas de plantilla para dinamizar la estructura HTML con PHP</p>
    <div class="row cards">
        <div class="card">
            <div class="section">
            <h3>Directiva if</h3>
            </div>
            <div class="section content">
                <p>`@if(..condición)`</p>
                <p>     Contenido ... </p>
                <p>@else</p>
                <p>     Si no contenido ... </p>
                <p>@endif</p>
            </div>
        </div>
        <div class="card">
            <div class="section">
            <h3>Directiva for</h3>
            </div>
            <div class="section content">
                <p>`@for({"a":1,"b":2,"c":3})`</p>
                <p>Contenido ... </p>
                <p>@endfor</p>
            </div>
        </div>
        <div class="card">
            <div class="section">
            <h3>Directiva include</h3>
            </div>
            <div class="section content">
                <p>`@include(url relativa)`</p>
            </div>
        </div>
    </div>
</section>