<section compile='false'> 
    <h2>
        Componentes Skeleton
    </h2>
    Los componentes son trozos de codigo independientes que generan un objeto html con características singulares. <br>
    Estos pueden ser reutilizados tantas veces como se desee. <br>
    Ayudan a crear aplicaciones más fáciles de diseñar y mantener. <br>

    <h3>Estructura básica de un componente Skeleton</h3>
    <ul>
        <li>
            m-component.phtml
            <pre>
            &lt;component id="{--id}"&gt;
                Código html & bone... 
                --content
                $$atr1
                $$atr2
                &lt;style lang="{less|sassc}" scoped&gt;
                    Código css, less, sassc ... 
                &lt;style&gt;
                &lt;script scope&gt;
                    const el = document.getElementById('--id') 
                &lt;script&gt;
            &lt;/component&gt;
            </pre>
        </li>
        <li>
            index.phtml <br>
            <pre>
                &lt;m-component id="" atr1="" atr2=""&gt;{Codigo...}&lt;/m-component&gt;
            </pre>
        </li>

    </ul>
    <div class="">
        La forma de crearlo es en un archivo con el nombre del componente que se desea. <br>
        Se debe iniciar y acabar con el pseudo-tag component <code>&lt;component id=""&gt;Codigo...&lt;/component&gt;</code>. <br>
        Dentro de el incluiremos la estructura html, js y css si se desea, y será precompilada con las directivas Bone. <br>

        Podemos encapsularle unos estilos propios mediante el tag <code>&lt;style lang="" scoped&gt;&lt;style&gt;</code> con el atributo lang se declarará el sublenguaje que se esté empleando: Lesscss, Sass etc.. <br>
        Para añadir la funcionalidad al componente se declara la etiqueta &lt;script scope&gt;&lt;script&gt; <br>

        Los atributos que se le pasan al componente a su llamada se declaran como variables Bone. 
    </div>

    <h3>El elemento Component</h3>
    <div>

        El componente ha de contar con un identificador único por lo que si no es declarado se le asigna uno. <br>
        La directiva <code>--id</code> proporcionará el id del elemento. <br>
        La directiva <code>--content</code> proporcina el contenido que se encuentra entre las etiquetas cuando se declara el componente. ej: <br>

        index.phtml <br>
        <pre>
            <code>
                &lt;my-component id=""&gt; <br>
                    Contenido en la declaración de mi componente <br>
                &lt;/my-component&gt; <br>
            </code>
        </pre>
        my-component.phtml
        <pre>
            <code>
                &lt;component id="--id"&lt;
                    &lt;div&gt;
                        --content
                    &lt;/div&gt;
                &lt;/component&gt;
            </code>
        </pre>


    </div>
</section>