<section>
    <h2>Peticiones GET</h2>
    <p>Carga de páginas modulares</p>
    <p>La navegación se realiza mediante peticiones parciales de las subpaginas, en Skeleton son secciones,  evitando la necesidad de recargar la totalidad de las paginas web y todos los arhivos necesarios para su correcto funcionamiento.</p>
    <div class="">
        <form id="form" action="action" method="post">
            <input type="text" name="input" id="input">
            <input type="submit" value="Aceptar">
        </form>
        <div id="buzon"></div>
    </div>
</section>