<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Expires" content="0">
    <meta http-equiv="Last-Modified" content="0">
    <meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
    <meta http-equiv="Pragma" content="no-cache">

    <!-- FontIcons -->
    <!-- <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css"> -->
    <!-- css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mini.css/3.0.1/mini-default.min.css">
    <!-- <link rel="stylesheet" href="https://cdn.rawgit.com/Chalarangelo/mini.css/v3.0.1/dist/mini-default.min.css"> -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <title>Skeleton Framework</title>
</head>

<body>
    <div class="header">
        <h1>Skeleton Framework AJAX-PHP</h1>
    </div>
    <div class="leftcolumn">
        <main>
            Aquºi se carga todo
            <section id="main" class="">
                <h3>Características</h3>
                <ul>
                    <li>Modular</li>
                    <li>Rápido</li>
                    <li>Altamente reutilizable</li>
                </ul>
            </section>
        </main>
        <m-btn onclick="app.getView(`page12`)">click me</m-btn>
    </div>
    <div class="rightcolumn">
        <div class="card">
            <h2>Componentes tipo botón</h2>
            <m-btn-success label="Pulsame" onclick="alert(`¡Esto es un ejemplo de un componente en acción!`)"></m-btn-success>
            <m-btn-cancel label="Pulsame" onclick="alert(`¡Esto es un componente hermano!`)"></m-btn-cancel>
        </div>
        <div class="card">
            <h2>About Me</h2>
            <div class="fakeimg" style="height:100px;">Image</div>
            <p>Some text about__construct me in culpa qui officia deserunt mollit anim..</p>
        </div>
    </div>
    <div class="footer">
        <a href="https://nestorpons.github.io/skeletonPHP/site/">Manual SkeletonPHP</a>
    </div>
</body>

</html>