<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Expires" content="0">
    <meta http-equiv="Last-Modified" content="0">
    <meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
    <meta http-equiv="Pragma" content="no-cache">

    <!-- FontIcons -->
    <!-- <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css"> -->
    <!-- css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mini.css/3.0.1/mini-default.min.css">
    <!-- <link rel="stylesheet" href="https://cdn.rawgit.com/Chalarangelo/mini.css/v3.0.1/dist/mini-default.min.css"> -->
    <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> -->

    <title>Bienvenida</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-2"></div>
            <div class="col-sm-12 col-md-5 col-lg-7">

                <section id="principal" class="principal">
                    <div>
                        <h1>SKELETON FRAMEWORK</h1>
                        <p>
                            Marco de trabajo PHP, HTML, AJAX, JS mediante componentes encapsulados.
                        </p>

                        <div class="collapse">
                            <input type="checkbox" id="collapse-section1" checked aria-hidden="true">
                            <label for="collapse-section1" aria-hidden="true">Framworks CSS y JS</label>
                            <div>
                                <p>Puedes incorporar los Frameworks CSS y JS que más te gusten</p>
                                <p>En el proyecto se trabaja con MINICSS el cual es libiano y totalmente personalizable con todo aquello que es indispensable para cualquier proyecto</p>
                            </div>
                            <input type="checkbox" id="collapse-section2" aria-hidden="true">
                            <label for="collapse-section2" aria-hidden="true">Collapse section 2</label>
                            <div>
                                <p>This is the second section of the collapse</p>
                            </div>
                        </div>
                    </div>
                </section>

            </div>
            <div class="col-sm-12 col-md-4 col-lg-3"></div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-2"></div>
            <div class="col-sm-12 col-md-5 col-lg-7">
                <p>Demostración de encapsulación de componentes.</p>
                <div class="card small">
                    <m-template-component label="Pulse en este label"></m-template-component>
                </div>
                <div class="card small warning">
                    <label> Este label carece de acción y de estilos propios </label>
                </div>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-3"></div>
        </div>
    </div>

</body>

</html>