<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Expires" content="0">
    <meta http-equiv="Last-Modified" content="0">
    <meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
    <meta http-equiv="Pragma" content="no-cache">

    <!-- FontIcons -->
    <!-- <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css"> -->
    <!-- css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mini.css/3.0.1/mini-default.min.css">
    <!-- <link rel="stylesheet" href="https://cdn.rawgit.com/Chalarangelo/mini.css/v3.0.1/dist/mini-default.min.css"> -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <title>Skeleton Framework</title>
</head>

<body>
    <div class="header">
        <h1 class="elegantshadow">Skeleton</h1>
        <dd>
            <em>Framework PHP</em><br>
            <em>Página creada con Skeleton y su lenguaje de plantillas Bone</em>
</dd>
    <hr><hr>
    </div>
    <div>
        Todo son objetos con las directivas Bone. <br>
        Los objetos Skeleton son reutilizables, minimizan y homogenizan todo muestro código. <br>
        Bone es el sublenguaje php que   y dinamiza el codigo html. <br>
        <a href="https://nestorpons.github.io/skeletonPHP/site/">Consulta el manual</a><br>
        <a href="https://github.com/nestorPons/skeletonPHP">Vista el proyecto en Github</a><br>
    </div>
    <main>
        @include(test.phtml)
    </main>
</body>

</html>