<!-- Encapsulado en el tag component-->
<component id="--id" class="">
    <!-- Estructura HTML del componente -->
    <label class="bordered">Atributo label: $$label</label>
    <span>--content</span>
    <!-- Estilos personales del componente -->

    <style scoped>
        label{
            display: block;
            color: green;
            cursor: pointer;
        }
        .toggled{
            color: red !important; 
            font-size: 3rem;
        }
    </style>
    <ul>
        @for($$mydataobject)
            <li>$$key $$value</li>
        @endfor
    </ul>
        
    <!-- Comportamiento del componente -->
    <script scoped>
        // Necesario para la correcta identificación del componente
        const el = document.getElementById('--id')

        el.onclick = e => {
            e.stopPropagation();
            el.className = 'toggled' == el.className ? '' : 'toggled';
        }

    </script>
    
</component>