<component id="--id">
    <m-checkbox id="--id_present" class='$$class' label="$$label" name='$$cb_name' value='$$value' />
    <m-input id="--id__input" type="date" label="$$caption" name="$$in_name" />
    
    <style>
        #--id {
            display: inline-flex;
            align-items: center;
        }
        #--id_present{
            display: flex;
        }
        #--id_present input[type="checkbox"] {
                margin: 10px;
            }
        #--id>component {
            margin: 5px;
        }
    </style>
</component>