<component id="--id" class="row $$hidden" >  
    <label for="--id_input" class="$$classLabel">$$label</label>
    <input 
        id ="--id_input"
        type = "$$type" 
        class="$$class" placeholder="$$placeholder" 
        style="$$style" name = "$$name" tile = "$$tile"
        pattern = "$$pattern"
        @if ($$for) for = "$$for" @endif 
        @if ($$maxlength) maxlength = "$$maxlength" @endif
        @if ($$minlength) minlength = "$$minlength" @endif
        default = "$$default" value = "$$value" 
        list = "$$list" tabindex = "$$tabindex" 
        onfocus = "$$onfocus" onblur = "$$onblur" onclick="$$onclick"
        onkeypress = "$$onkeypress" onkeydown = "$$onkeydown" onkeyup = "$$onkeyup"
        onchange = "$$onchange" $$required $$disabled readonly="$$readonly" $$checked  
    />
    @if ($$icon) <i id="icon$$id" class="lnr lnr-$$icon"></i> @endif
    <style lang="less" scoped>
        label {
            z-index: 101;
        }
        input{
            /* Aplicamos el color y el tamaño del padre */
            font-size : inherit; 
            color: inherit;
            width: 100%;
            &[type="color"]{
                margin-left: 13ch;
            }
        }
    </style>
    
</component>
