<component id="--id">
  
  <input type="checkbox" id="control_--id" class="modal" >
  <div>
    <div class="card card-modal" id="card--id">
      
      <label for="control_--id" class="lnr lnr-cross-circle icon-close"></label>
      
      <h1 id="tileModal--id" class="tile"></h1>
      
      --content
    </div>
  </div>
  <style lang="less" scoped>
    .icon-close {
      position: absolute;
      right: -12px;
      font-size: 26px;
      top: -13px;
      background: white;
      z-index: 1000;
      border-radius: 87%;
      width: 6px;
      height: 14px;
      text-align: center;
      vertical-align: middle;
      display: flex;
      justify-content: center;
      align-items: center;

      &::before {
        content: "\e880";
      }

      @media(max-width: 375px) {
        top: 0;
        right: 0;
      }
    }

    h1 {
      text-align: center;
    }
  </style>
  
</component>