<!-- Encapsulado en el tag component-->
<component id="--id" class="">
    <!-- Estructura HTML del componente -->
    <label class="bordered">Componente ejemplo: $$label</label>
    <!-- Estilos personales del componente -->
    <style scoped>
        label{
            display: block;
            color: red;
            cursor: pointer;
        }
    </style>
    <!-- Comportamiento del componente -->
    <script scoped>
        // Necesario para la correcta identificación del componente
        const $this = document.getElementById('--id') 

        $this.onclick = e => {
            e.stopPropagation();
            alert('Ejemplo de comportamiento de un componente');
        }

    </script>
    
</component>